(define (domain qt_quiz_domain)
    (:requirements :strips :typing :fluents :action-costs :disjunctive-preconditions :negative-preconditions)

    (:predicates
        (interaction_started)
        (interaction_finished)

        (quiz_introduced)
        (quiz_finished)

        (emotion_checked)

        (can_conversate)
        (answered_wrong)
    )

    (:functions
        (robot_e)
        (robot_p)
        (robot_a)
        (human_e)
        (human_p)
        (human_a)

        (robot_e_sq)
        (robot_p_sq)
        (robot_a_sq)
        (human_e_sq)
        (human_p_sq)
        (human_a_sq)

        (alpha)
        (beta)
        (gamma)
        (total-cost)

        (difficulty)
        (right_answers)
        (wrong_answers)

        (n_questions)

        (ask_coeff)
        (mime_coeff)
        (sound_coeff)
        (image_coeff)

        (sound_easy_coeff)
        (sound_medium_coeff)
        (sound_hard_coeff)
        (image_easy_coeff)
        (image_medium_coeff)
        (image_hard_coeff)
        (ask_easy_coeff)
        (ask_medium_coeff)
        (ask_hard_coeff)
        (mime_easy_coeff)
    )


    (:action check_emotion
        :parameters ()
        :precondition (not (emotion_checked))
        :effect (emotion_checked)
    )

    (:action greet_warmly
        :parameters ()
        :precondition (not (interaction_started))
        :effect (interaction_started)
    )

    (:action say_goodbye
        :parameters ()
        :precondition (and
            (interaction_started)
            (quiz_finished)
         )
        :effect (and 
            (not (interaction_started))
            (interaction_finished)
        )
    )

    (:action introduce_game
        :parameters ()
        :precondition (and 
            (interaction_started)
            (not (quiz_introduced))
        )
        :effect (and 
            (quiz_introduced)
            (not (emotion_checked))
            (assign (human_e) 3.44)
            (assign (human_p) 2.93)
            (assign (human_a) 0.92)
            (assign (human_e_sq) 11.8336)
            (assign (human_p_sq) 8.5849)
            (assign (human_a_sq) 0.8464)
         )
    )

    (:action conclude_game
        :parameters ()
        :precondition (and 
            (interaction_started)
            (quiz_introduced)
            (= (n_questions) 4)
        )
        :effect (and 
            (not (quiz_introduced))
            (quiz_finished)
        )
    )


    (:action conversate
        :parameters ()
        :precondition (and
            (interaction_started)
            (quiz_introduced)
            (emotion_checked)
            (can_conversate)
            (>= (human_e) 0.0)
        )
        :effect (and
            (increase (total-cost)
                (* 1.0
                    (+ (* 1.0
                            (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                        (+ (* 1.0
                                (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                    (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                    (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))
                            (+ (* 1.0
                                    (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                        (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                        (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                                (* 1.0
                                    (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                        (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                        (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464))))))))))
            (not (emotion_checked))
            (not (can_conversate))
            (assign (robot_e) 3.44)
            (assign (robot_p) 2.93)
            (assign (robot_a) 0.92)
            (assign (robot_e_sq) 11.8336)
            (assign (robot_p_sq) 8.5849)
            (assign (robot_a_sq) 0.8464)
            (assign (human_e) 3.44)
            (assign (human_p) 2.93)
            (assign (human_a) 0.92)
            (assign (human_e_sq) 11.8336)
            (assign (human_p_sq) 8.5849)
            (assign (human_a_sq) 0.8464)
        )  
    )


    ;; QUESTION RELATED ACTIONS

    (:action sound_easy
        :parameters ()
        :precondition (and 
            (interaction_started)
            (quiz_introduced)
            (emotion_checked)
            (= (difficulty) 0)
            (>= (human_e) 0.0)
            (not (can_conversate))
            (not (answered_wrong))
        )
        :effect (and
            (increase (total-cost)
                (* (sound_coeff)
                    (* (sound_easy_coeff) (+ (* 1.0
                            (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                        (+ (* 1.0
                                (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                    (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                    (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))
                            (+ (* 1.0
                                    (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                        (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                        (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                                (* 1.0
                                    (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                        (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                        (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))))))))
            (not (emotion_checked))
            (increase (n_questions) 1)
            (assign (robot_e) 3.44)
            (assign (robot_p) 2.93)
            (assign (robot_a) 0.92)
            (assign (robot_e_sq) 11.8336)
            (assign (robot_p_sq) 8.5849)
            (assign (robot_a_sq) 0.8464)
            (assign (human_e) 3.44)
            (assign (human_p) 2.93)
            (assign (human_a) 0.92)
            (assign (human_e_sq) 11.8336)
            (assign (human_p_sq) 8.5849)
            (assign (human_a_sq) 0.8464)
        )
    )

    (:action sound_medium
        :parameters ()
        :precondition (and 
            (interaction_started)
            (quiz_introduced)
            (emotion_checked)
            (= (difficulty) 1)
            (>= (human_e) 0.0)
            (not (can_conversate))
            (not (answered_wrong))
        )
        :effect (and
            (increase (total-cost)
                (* (sound_coeff)
                    (* (sound_medium_coeff) (+ (* 1.0
                            (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                        (+ (* 1.0
                                (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                    (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                    (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))
                            (+ (* 1.0
                                    (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                        (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                        (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                                (* 1.0
                                    (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                        (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                        (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))))))))
            (not (emotion_checked))
            (increase (n_questions) 1)
            (assign (robot_e) 3.44)
            (assign (robot_p) 2.93)
            (assign (robot_a) 0.92)
            (assign (robot_e_sq) 11.8336)
            (assign (robot_p_sq) 8.5849)
            (assign (robot_a_sq) 0.8464)
            (assign (human_e) 3.44)
            (assign (human_p) 2.93)
            (assign (human_a) 0.92)
            (assign (human_e_sq) 11.8336)
            (assign (human_p_sq) 8.5849)
            (assign (human_a_sq) 0.8464)
        )
    )

    (:action sound_hard
        :parameters ()
        :precondition (and 
            (interaction_started)
            (quiz_introduced)
            (emotion_checked)
            (= (difficulty) 2)
            (>= (human_e) 0.0)
            (not (can_conversate))
            (not (answered_wrong))
        )
        :effect (and
            (increase (total-cost)
                (* (sound_coeff)
                    (* (sound_hard_coeff) (+ (* 1.0
                            (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                        (+ (* 1.0
                                (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                    (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                    (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))
                            (+ (* 1.0
                                    (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                        (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                        (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                                (* 1.0
                                    (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                        (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                        (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))))))))
            (not (emotion_checked))
            (increase (n_questions) 1)
            (assign (robot_e) 3.44)
            (assign (robot_p) 2.93)
            (assign (robot_a) 0.92)
            (assign (robot_e_sq) 11.8336)
            (assign (robot_p_sq) 8.5849)
            (assign (robot_a_sq) 0.8464)
            (assign (human_e) 3.44)
            (assign (human_p) 2.93)
            (assign (human_a) 0.92)
            (assign (human_e_sq) 11.8336)
            (assign (human_p_sq) 8.5849)
            (assign (human_a_sq) 0.8464)
        )
    )


    (:action image_easy
        :parameters ()
        :precondition (and 
            (interaction_started)
            (quiz_introduced)
            (emotion_checked)
            (= (difficulty) 0)
            (>= (human_e) 0.0)
            (not (can_conversate))
            (not (answered_wrong))
        )
        :effect (and 
            (increase (total-cost)
                (* (image_coeff)
                    (* (image_easy_coeff) (+ (* 1.0
                            (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                        (+ (* 1.0
                                (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                    (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                    (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))
                            (+ (* 1.0
                                    (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                        (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                        (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                                (* 1.0
                                    (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                        (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                        (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))))))))
            (not (emotion_checked))
            (increase (n_questions) 1)
            (assign (robot_e) 3.44)
            (assign (robot_p) 2.93)
            (assign (robot_a) 0.92)
            (assign (robot_e_sq) 11.8336)
            (assign (robot_p_sq) 8.5849)
            (assign (robot_a_sq) 0.8464)
            (assign (human_e) 3.44)
            (assign (human_p) 2.93)
            (assign (human_a) 0.92)
            (assign (human_e_sq) 11.8336)
            (assign (human_p_sq) 8.5849)
            (assign (human_a_sq) 0.8464)
        )
    )

    (:action image_medium
        :parameters ()
        :precondition (and 
            (interaction_started)
            (quiz_introduced)
            (emotion_checked)
            (= (difficulty) 1)
            (>= (human_e) 0.0)
            (not (can_conversate))
            (not (answered_wrong))
        )
        :effect (and 
            (increase (total-cost)
                (* (image_coeff)
                    (* (image_medium_coeff) (+ (* 1.0
                            (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                        (+ (* 1.0
                                (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                    (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                    (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))
                            (+ (* 1.0
                                    (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                        (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                        (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                                (* 1.0
                                    (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                        (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                        (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))))))))
            (not (emotion_checked))
            (increase (n_questions) 1)
            (assign (robot_e) 3.44)
            (assign (robot_p) 2.93)
            (assign (robot_a) 0.92)
            (assign (robot_e_sq) 11.8336)
            (assign (robot_p_sq) 8.5849)
            (assign (robot_a_sq) 0.8464)
            (assign (human_e) 3.44)
            (assign (human_p) 2.93)
            (assign (human_a) 0.92)
            (assign (human_e_sq) 11.8336)
            (assign (human_p_sq) 8.5849)
            (assign (human_a_sq) 0.8464)
        )
    )

    (:action image_hard
        :parameters ()
        :precondition (and 
            (interaction_started)
            (quiz_introduced)
            (emotion_checked)
            (= (difficulty) 2)
            (>= (human_e) 0.0)
            (not (can_conversate))
            (not (answered_wrong))
        )
        :effect (and 
            (increase (total-cost)
                (* (image_coeff)
                    (* (image_hard_coeff) (+ (* 1.0
                            (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                        (+ (* 1.0
                                (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                    (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                    (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))
                            (+ (* 1.0
                                    (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                        (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                        (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                                (* 1.0
                                    (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                        (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                        (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))))))))
            (not (emotion_checked))
            (increase (n_questions) 1)
            (assign (robot_e) 3.44)
            (assign (robot_p) 2.93)
            (assign (robot_a) 0.92)
            (assign (robot_e_sq) 11.8336)
            (assign (robot_p_sq) 8.5849)
            (assign (robot_a_sq) 0.8464)
            (assign (human_e) 3.44)
            (assign (human_p) 2.93)
            (assign (human_a) 0.92)
            (assign (human_e_sq) 11.8336)
            (assign (human_p_sq) 8.5849)
            (assign (human_a_sq) 0.8464)
        )
    )

    (:action ask_easy
        :parameters ()
        :precondition (and 
            (interaction_started)
            (quiz_introduced)
            (emotion_checked)
            (= (difficulty) 0)
            (>= (human_e) 0.0)
            (not (can_conversate))
            (not (answered_wrong))
        )
        :effect (and
            (increase (total-cost)
                (* (ask_coeff)
                    (* (ask_easy_coeff) (+ (* 1.0
                            (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                        (+ (* 1.0
                                (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                    (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                    (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))
                            (+ (* 1.0
                                    (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                        (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                        (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                                (* 1.0
                                    (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                        (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                        (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))))))))
            (not (emotion_checked))
            (increase (n_questions) 1)
            (assign (robot_e) 3.44)
            (assign (robot_p) 2.93)
            (assign (robot_a) 0.92)
            (assign (robot_e_sq) 11.8336)
            (assign (robot_p_sq) 8.5849)
            (assign (robot_a_sq) 0.8464)
            (assign (human_e) 3.44)
            (assign (human_p) 2.93)
            (assign (human_a) 0.92)
            (assign (human_e_sq) 11.8336)
            (assign (human_p_sq) 8.5849)
            (assign (human_a_sq) 0.8464)
        )
    )

    (:action ask_medium
        :parameters ()
        :precondition (and 
            (interaction_started)
            (quiz_introduced)
            (emotion_checked)
            (= (difficulty) 1)
            (>= (human_e) 0.0)
            (not (can_conversate))
            (not (answered_wrong))
        )
        :effect (and
            (increase (total-cost)
                (* (ask_coeff)
                    (* (ask_medium_coeff) (+ (* 1.0
                            (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                        (+ (* 1.0
                                (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                    (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                    (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))
                            (+ (* 1.0
                                    (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                        (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                        (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                                (* 1.0
                                    (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                        (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                        (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))))))))
            (not (emotion_checked))
            (increase (n_questions) 1)
            (assign (robot_e) 3.44)
            (assign (robot_p) 2.93)
            (assign (robot_a) 0.92)
            (assign (robot_e_sq) 11.8336)
            (assign (robot_p_sq) 8.5849)
            (assign (robot_a_sq) 0.8464)
            (assign (human_e) 3.44)
            (assign (human_p) 2.93)
            (assign (human_a) 0.92)
            (assign (human_e_sq) 11.8336)
            (assign (human_p_sq) 8.5849)
            (assign (human_a_sq) 0.8464)
        )
    )

    (:action ask_hard
        :parameters ()
        :precondition (and 
            (interaction_started)
            (quiz_introduced)
            (emotion_checked)
            (= (difficulty) 2)
            (>= (human_e) 0.0)
            (not (can_conversate))
            (not (answered_wrong))
        )
        :effect (and
            (increase (total-cost)
                (* (ask_coeff)
                    (* (ask_hard_coeff) (+ (* 1.0
                            (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                        (+ (* 1.0
                                (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                    (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                    (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))
                            (+ (* 1.0
                                    (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                        (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                        (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                                (* 1.0
                                    (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                        (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                        (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))))))))
            (not (emotion_checked))
            (increase (n_questions) 1)
            (assign (robot_e) 3.44)
            (assign (robot_p) 2.93)
            (assign (robot_a) 0.92)
            (assign (robot_e_sq) 11.8336)
            (assign (robot_p_sq) 8.5849)
            (assign (robot_a_sq) 0.8464)
            (assign (human_e) 3.44)
            (assign (human_p) 2.93)
            (assign (human_a) 0.92)
            (assign (human_e_sq) 11.8336)
            (assign (human_p_sq) 8.5849)
            (assign (human_a_sq) 0.8464)
        )
    )

    (:action mime_easy
        :parameters ()
        :precondition (and 
            (interaction_started)
            (quiz_introduced)
            (emotion_checked)
            (= (difficulty) 0)
            (>= (human_e) 0.0)
            (not (can_conversate))
            (not (answered_wrong))
        )
        :effect (and 
            (increase (total-cost)
                (* (mime_coeff)
                    (* (mime_easy_coeff) (+ (* 1.0
                            (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                        (+ (* 1.0
                                (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                    (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                    (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))
                            (+ (* 1.0
                                    (+ (+ (robot_e_sq) (+ (* -6.88 (robot_e)) 11.8336))
                                        (+ (+ (robot_p_sq) (+ (* -5.86 (robot_p)) 8.5849))
                                        (+ (robot_a_sq) (+ (* -1.84 (robot_a)) 0.8464)))))
                                (* 1.0
                                    (+ (+ (human_e_sq) (+ (* -6.88 (human_e)) 11.8336))
                                        (+ (+ (human_p_sq) (+ (* -5.86 (human_p)) 8.5849))
                                        (+ (human_a_sq) (+ (* -1.84 (human_a)) 0.8464)))))))))))
            (not (emotion_checked))
            (increase (n_questions) 1)
            (assign (robot_e) 3.44)
            (assign (robot_p) 2.93)
            (assign (robot_a) 0.92)
            (assign (robot_e_sq) 11.8336)
            (assign (robot_p_sq) 8.5849)
            (assign (robot_a_sq) 0.8464)
            (assign (human_e) 3.44)
            (assign (human_p) 2.93)
            (assign (human_a) 0.92)
            (assign (human_e_sq) 11.8336)
            (assign (human_p_sq) 8.5849)
            (assign (human_a_sq) 0.8464)
        )
    )

    (:action comfort
        :parameters ()
        :precondition (and 
            (quiz_introduced)
            (emotion_checked)
            (> (robot_e) 0.0)
            (or (< (human_p) 0.0) (answered_wrong))
        )
        :effect (and 
            (increase (total-cost)
                (* 1.0
                    (+ 
                        (* 1.0 
                            (+ (+ (robot_e_sq) (robot_p_sq)) (robot_a_sq))
                        )
                        (+  (* 1.0 
                                (+ (+ (human_e_sq) (+ (* 4.58 (human_e)) 5.2441))
                                (+ (+ (human_p_sq) (+ (* 2.88 (human_p)) 2.0736))
                                (+ (human_a_sq) (+ (* 4.08 (human_a)) 4.1616))))
                            )
                        (+ (* 1.0 
                                (+ (+ (robot_e_sq) (+ (* -1.16 (robot_e)) 0.3364))
                                (+ (+ (robot_p_sq) (+ (* -1.50 (robot_p)) 0.5625))
                                (+ (robot_a_sq) (+ (* -1.12 (robot_a)) 0.3136))))
                            )
                            (* 1.0 
                                (+ (+ (human_e_sq) (+ (* -1.16 (human_e)) 0.3364))
                                (+ (+ (human_p_sq) (+ (* -1.50 (human_p)) 0.5625))
                                (+ (human_a_sq) (+ (* -1.12 (human_a)) 0.3136))))
                            )
                        ))
                    )
                )
            )  
            (assign (robot_e) 3.44)
            (assign (robot_p) 2.93)
            (assign (robot_a) 0.92)
            (assign (robot_e_sq) 11.8336)
            (assign (robot_p_sq) 8.5849)
            (assign (robot_a_sq) 0.8464)
            (assign (human_e) 3.44)
            (assign (human_p) 2.93)
            (assign (human_a) 0.92)
            (assign (human_e_sq) 11.8336)
            (assign (human_p_sq) 8.5849)
            (assign (human_a_sq) 0.8464)
            (not (answered_wrong))
        )
    )


)
